---
- name: copy the redis configuration
  template: src=redis.conf.j2 dest=/etc/redis/redis.conf
  notify: restart redis slave

- name: start the redis server
  service: name=redis-server state=started enabled=yes 